GET http://localhost:2024
Authorization: Bearer 

### REGISTER
POST http://localhost:2024/auth/register
Content-Type: application/json

{
    "email": "email@gmail.com",
    "name": "Princewill Inyang",
    "password": "M5@TsHT~A9tM$gA"
}

### LOG IN
POST http://localhost:2024/auth/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "M5@TsHT~A9tM$gA"
}

### VERIFY EMAIL
POST http://localhost:2024/auth/verify-email
Content-Type: application/json

{
    "email": "princewillingoo@gmail.com",
    "otp": "264568"
}

### RESEND OTP
POST http://localhost:2024/auth/resend-otp
Content-Type: application/json

{
    "email": "princewillingoo@gmail.com"
}

### REFRESH TOKEN
POST http://localhost:2024/auth/refresh-token
Content-Type: application/json

{
    "token": ""
}

### FORGOT PASSWORD
POST http://localhost:2024/auth/forgot-password
Content-Type: application/json

{
    "email": "princewillingoo@gmail.com"
}

### RESET PASSWORD
GET http://localhost:2024/auth/reset-password?token=92f5ed4a-7ddb-4d6f-a7a6-221c6e747ed6

### PASSWORD RESET
POST http://localhost:2024/auth/password-reset
Content-Type: application/json

{
    "token": "92f5ed4a-7ddb-4d6f-a7a6-221c6e747ed6",
    "userId": "4c2b1af6-75bf-4a95-b783-ffe7f693ed8a",
    "password": "M5@TsHT~A9tM$iJ"
}

### LOG OUT
DELETE http://localhost:2024/auth/logout