GET http://localhost:2024
Authorization: Bearer 

### REGISTER
POST http://localhost:2024/auth/register
Content-Type: application/json

{
    "email": "email@gmail.com",
    "name": "Princewill Inyang",
    "password": "M5@TsHT~A9tM$gA"
}

### LOG IN
POST http://localhost:2024/auth/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "M5@TsHT~A9tM$gA"
}

### VERIFY EMAIL
POST http://localhost:2024/auth/verify-email
Content-Type: application/json

{
    "email": "princewillingoo@gmail.com",
    "otp": "264568"
}

### RESEND OTP
POST http://localhost:2024/auth/resend-otp
Content-Type: application/json

{
    "email": "princewillingoo@gmail.com"
}

### REFRESH TOKEN
POST http://localhost:2024/auth/refresh-token
Content-Type: application/json

{
    "token": ""
}

### LOG OUT
DELETE http://localhost:2024/auth/logout